# Generated by Django 6.1 on 2026-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Test User', max_length=150),
            preserve_default=False,
        ),
    ]
