# Generated by Django 6.1 on 2026-09-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_created_at_url_title_url_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='code',
        ),
    ]
